### ISSUE TITLE
[0.3.0][0.4.0] TypeScript: Global install doesn't work

### ISSUE THREAD

**Issue by Semigradsky** [rauschma/iterator-helpers-polyfill#1]
After 0.3.0 version `import '@rauschma/iterator-helpers-polyfill/install'` lead to `dist/install-polyfill.d.ts` which is empty:
```ts
export {};
//# sourceMappingURL=install-polyfill.d.ts.map
```

**Comment by rauschma** [comment]
Thanks for reporting this. Should be fixed now. Please reopen if it’s not.
